language: node_js

node_js:
  - "4.3.1"
  - "5.7.0"

before_install:
  - npm install -g gulp
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - bower install -F

script:
  - gulp build

after_script:
  - codeclimate < test/coverage/**/lcov.info
